"-----BEGIN CERTIFICATE-----" "\n"
"<line>" "\n"
"<line>" "\n"
"<line>" "\n"
"<line>" "\n"
"<line>" "\n"
"<line>" "\n"
"<line>" "\n"
"<line>" "\n"
"<line>" "\n"
"<line>" "\n"
"<line>" "\n"
"<line>" "\n"
"<line>" "\n"
"<line>" "\n"
"<line>" "\n"
"<line>" "\n"
"-----END CERTIFICATE-----" "\n"